# Generated by Django 5.1.5 on 2025-01-22 18:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_auditlogs_core_auditl_entity_1c2026_idx_and_more'),
        ('customers', '0011_rename_lookupcode_customer_lookup_code_and_more'),
        ('inventory', '0002_rename_createdbyuser_inventory_created_by_user_and_more'),
        ('logistics', '0003_rename_createdbyuser_address_created_by_user_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='inventory',
            name='inventory_i_license_54c5e7_idx',
        ),
        migrations.RemoveIndex(
            model_name='inventoryserialnumber',
            name='inventory_i_lookupC_e0a72f_idx',
        ),
        migrations.RemoveIndex(
            model_name='inventoryserialnumber',
            name='inventory_i_license_db47d1_idx',
        ),
        migrations.RemoveIndex(
            model_name='material',
            name='inventory_m_lookupC_15dd9b_idx',
        ),
        migrations.RemoveIndex(
            model_name='uom',
            name='inventory_u_lookupC_3b594e_idx',
        ),
        migrations.RenameField(
            model_name='inventory',
            old_name='lastUpdated',
            new_name='last_updated',
        ),
        migrations.RenameField(
            model_name='inventory',
            old_name='licensePlate',
            new_name='license_plate',
        ),
        migrations.RenameField(
            model_name='inventory',
            old_name='licensePlateID',
            new_name='license_plate_id',
        ),
        migrations.RenameField(
            model_name='inventory',
            old_name='updatedByUser',
            new_name='updated_by_user',
        ),
        migrations.RenameField(
            model_name='inventory',
            old_name='vendorLot',
            new_name='vendor_lot',
        ),
        migrations.RenameField(
            model_name='inventoryserialnumber',
            old_name='licensePlate',
            new_name='license_plate',
        ),
        migrations.RenameField(
            model_name='inventoryserialnumber',
            old_name='lookupCode',
            new_name='lookup_code',
        ),
        migrations.RenameField(
            model_name='material',
            old_name='isSerialized',
            new_name='is_serialized',
        ),
        migrations.RenameField(
            model_name='material',
            old_name='lookupCode',
            new_name='lookup_code',
        ),
        migrations.RenameField(
            model_name='uom',
            old_name='lookupCode',
            new_name='lookup_code',
        ),
        migrations.AddIndex(
            model_name='inventory',
            index=models.Index(fields=['license_plate_id'], name='inventory_i_license_f141fd_idx'),
        ),
        migrations.AddIndex(
            model_name='inventoryserialnumber',
            index=models.Index(fields=['lookup_code'], name='inventory_i_lookup__01291c_idx'),
        ),
        migrations.AddIndex(
            model_name='inventoryserialnumber',
            index=models.Index(fields=['license_plate'], name='inventory_i_license_bdd42c_idx'),
        ),
        migrations.AddIndex(
            model_name='material',
            index=models.Index(fields=['lookup_code'], name='inventory_m_lookup__f5583c_idx'),
        ),
        migrations.AddIndex(
            model_name='uom',
            index=models.Index(fields=['lookup_code'], name='inventory_u_lookup__c4fc38_idx'),
        ),
    ]
