# Generated by Django 5.1.5 on 2025-01-27 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_remove_inventory_inventory_i_license_54c5e7_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='license_plate',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='location',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
