# Generated by Django 5.1.5 on 2025-01-27 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_alter_inventory_license_plate_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventory',
            name='last_updated',
        ),
        migrations.RemoveField(
            model_name='inventory',
            name='updated_by_user',
        ),
    ]
