# Generated by Django 5.1.5 on 2025-01-27 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_remove_material_price_materialpricehistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materialpricehistory',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
