# Generated by Django 5.1.5 on 2025-01-28 15:59

import apps.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0010_alter_materialpricehistory_end_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventoryserialnumber',
            name='lookup_code',
            field=models.CharField(help_text='Serial number', max_length=50, unique=True, validators=[apps.core.validators.validate_lookup_code]),
        ),
        migrations.AlterField(
            model_name='material',
            name='lookup_code',
            field=models.CharField(max_length=50, unique=True, validators=[apps.core.validators.validate_lookup_code]),
        ),
        migrations.AlterField(
            model_name='uom',
            name='lookup_code',
            field=models.CharField(max_length=20, unique=True, validators=[apps.core.validators.validate_lookup_code]),
        ),
    ]
