# Generated by Django 5.1.5 on 2025-01-28 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0012_materialtype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='type',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
