# Generated by Django 5.1.5 on 2025-01-22 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='entityType',
            field=models.CharField(choices=[('customer', 'Customer'), ('warehouse', 'Warehouse'), ('recipient', 'Recipient')], max_length=20),
        ),
    ]
