# Generated by Django 5.1.5 on 2025-01-22 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0002_alter_address_entitytype'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='createdByUser',
            new_name='created_by_user',
        ),
        migrations.RenameField(
            model_name='address',
            old_name='createdDate',
            new_name='created_date',
        ),
        migrations.RenameField(
            model_name='address',
            old_name='modifiedByUser',
            new_name='modified_by_user',
        ),
        migrations.RenameField(
            model_name='address',
            old_name='modifiedDate',
            new_name='modified_date',
        ),
        migrations.RenameField(
            model_name='carrier',
            old_name='createdByUser',
            new_name='created_by_user',
        ),
        migrations.RenameField(
            model_name='carrier',
            old_name='createdDate',
            new_name='created_date',
        ),
        migrations.RenameField(
            model_name='carrier',
            old_name='modifiedByUser',
            new_name='modified_by_user',
        ),
        migrations.RenameField(
            model_name='carrier',
            old_name='modifiedDate',
            new_name='modified_date',
        ),
        migrations.RenameField(
            model_name='carrierservice',
            old_name='createdByUser',
            new_name='created_by_user',
        ),
        migrations.RenameField(
            model_name='carrierservice',
            old_name='createdDate',
            new_name='created_date',
        ),
        migrations.RenameField(
            model_name='carrierservice',
            old_name='modifiedByUser',
            new_name='modified_by_user',
        ),
        migrations.RenameField(
            model_name='carrierservice',
            old_name='modifiedDate',
            new_name='modified_date',
        ),
        migrations.RenameField(
            model_name='warehouse',
            old_name='createdByUser',
            new_name='created_by_user',
        ),
        migrations.RenameField(
            model_name='warehouse',
            old_name='createdDate',
            new_name='created_date',
        ),
        migrations.RenameField(
            model_name='warehouse',
            old_name='modifiedByUser',
            new_name='modified_by_user',
        ),
        migrations.RenameField(
            model_name='warehouse',
            old_name='modifiedDate',
            new_name='modified_date',
        ),
    ]
