# Generated by Django 5.1.5 on 2025-01-22 18:54

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_auditlogs_core_auditl_entity_1c2026_idx_and_more'),
        ('logistics', '0003_rename_createdbyuser_address_created_by_user_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='address',
            name='logistics_a_entityT_7345f1_idx',
        ),
        migrations.RemoveIndex(
            model_name='carrier',
            name='logistics_c_lookupC_40287b_idx',
        ),
        migrations.RemoveIndex(
            model_name='carrierservice',
            name='logistics_c_lookupC_d9c6e0_idx',
        ),
        migrations.RemoveIndex(
            model_name='warehouse',
            name='logistics_w_lookupC_985b4c_idx',
        ),
        migrations.RenameField(
            model_name='address',
            old_name='addressLine1',
            new_name='address_line_1',
        ),
        migrations.RenameField(
            model_name='address',
            old_name='addressLine2',
            new_name='address_line_2',
        ),
        migrations.RenameField(
            model_name='address',
            old_name='addressType',
            new_name='address_type',
        ),
        migrations.RenameField(
            model_name='address',
            old_name='attentionOf',
            new_name='attention_of',
        ),
        migrations.RenameField(
            model_name='address',
            old_name='entityID',
            new_name='entity_id',
        ),
        migrations.RenameField(
            model_name='address',
            old_name='entityType',
            new_name='entity_type',
        ),
        migrations.RenameField(
            model_name='address',
            old_name='postalCode',
            new_name='postal_code',
        ),
        migrations.RenameField(
            model_name='carrier',
            old_name='lookupCode',
            new_name='lookup_code',
        ),
        migrations.RenameField(
            model_name='carrierservice',
            old_name='lookupCode',
            new_name='lookup_code',
        ),
        migrations.RenameField(
            model_name='warehouse',
            old_name='lookupCode',
            new_name='lookup_code',
        ),
        migrations.AddIndex(
            model_name='address',
            index=models.Index(fields=['entity_type', 'entity_id'], name='logistics_a_entity__2b21b3_idx'),
        ),
        migrations.AddIndex(
            model_name='carrier',
            index=models.Index(fields=['lookup_code'], name='logistics_c_lookup__f37c87_idx'),
        ),
        migrations.AddIndex(
            model_name='carrierservice',
            index=models.Index(fields=['lookup_code'], name='logistics_c_lookup__74dcf8_idx'),
        ),
        migrations.AddIndex(
            model_name='warehouse',
            index=models.Index(fields=['lookup_code'], name='logistics_w_lookup__4d46a6_idx'),
        ),
    ]
