# Generated by Django 5.1.5 on 2025-01-23 21:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0006_contactaddress_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='attention_of',
        ),
    ]
