# Generated by Django 5.1.5 on 2025-01-23 21:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0007_remove_address_attention_of'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='address',
            name='logistics_a_entity__2b21b3_idx',
        ),
        migrations.RemoveField(
            model_name='address',
            name='entity_id',
        ),
        migrations.AddIndex(
            model_name='address',
            index=models.Index(fields=['entity_type'], name='logistics_a_entity__b89140_idx'),
        ),
    ]
