# Generated by Django 5.1.5 on 2025-01-24 19:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0011_alter_contact_addresses'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='contact_type',
        ),
    ]
