# Generated by Django 5.1.5 on 2025-02-05 16:18

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0014_alter_carrier_lookup_code_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='contact',
            index=models.Index(fields=['first_name'], name='logistics_c_first_n_88823e_idx'),
        ),
        migrations.AddIndex(
            model_name='contact',
            index=models.Index(fields=['last_name'], name='logistics_c_last_na_5b1bdb_idx'),
        ),
    ]
