# Generated by Django 5.1.5 on 2025-01-21 20:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='auditlogs',
            name='createdByUser',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='auditlogs',
            name='modifiedByUser',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_modified', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='auditlogs',
            name='userID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='audit_logs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='featureflags',
            name='createdByUser',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='featureflags',
            name='modifiedByUser',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_modified', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='logs',
            name='createdByUser',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='logs',
            name='modifiedByUser',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_modified', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='logs',
            name='userID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='activity_logs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='status',
            name='createdByUser',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='status',
            name='modifiedByUser',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_modified', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='types',
            name='createdByUser',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='types',
            name='modifiedByUser',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_modified', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='auditlogs',
            index=models.Index(fields=['entity', 'entityID', 'timestamp'], name='core_auditl_entity_1c2026_idx'),
        ),
        migrations.AddIndex(
            model_name='featureflags',
            index=models.Index(fields=['scope', 'scopeID'], name='core_featur_scope_3e28f6_idx'),
        ),
        migrations.AddIndex(
            model_name='logs',
            index=models.Index(fields=['entity', 'entityID', 'timestamp'], name='core_logs_entity_1d8b15_idx'),
        ),
        migrations.AddIndex(
            model_name='status',
            index=models.Index(fields=['code', 'statusType'], name='core_status_code_72b16b_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='status',
            unique_together={('code', 'statusType')},
        ),
        migrations.AddIndex(
            model_name='types',
            index=models.Index(fields=['entity', 'typeName'], name='core_types_entity_9a6892_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='types',
            unique_together={('entity', 'typeName')},
        ),
    ]
