# Generated by Django 5.1.5 on 2025-01-21 20:16

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdDate', models.DateTimeField(auto_now_add=True)),
                ('modifiedDate', models.DateTimeField(auto_now=True)),
                ('addressLine1', models.CharField(max_length=100)),
                ('addressLine2', models.CharField(blank=True, max_length=100)),
                ('city', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('country', models.CharField(max_length=50)),
                ('postalCode', models.CharField(max_length=20)),
                ('entityID', models.PositiveIntegerField(blank=True, help_text='ID of customer/warehouse', null=True)),
                ('entityType', models.CharField(choices=[('customer', 'Customer'), ('warehouse', 'Warehouse')], max_length=20)),
                ('addressType', models.CharField(choices=[('shipping', 'Shipping'), ('billing', 'Billing')], default='shipping', max_length=10)),
                ('notes', models.TextField(blank=True)),
                ('attentionOf', models.CharField(blank=True, max_length=100)),
                ('createdByUser', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('modifiedByUser', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_modified', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Addresses',
            },
        ),
        migrations.CreateModel(
            name='Carrier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdDate', models.DateTimeField(auto_now_add=True)),
                ('modifiedDate', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('lookupCode', models.CharField(max_length=50, unique=True, validators=[django.core.validators.MinLengthValidator(2)])),
                ('createdByUser', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('modifiedByUser', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_modified', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CarrierService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdDate', models.DateTimeField(auto_now_add=True)),
                ('modifiedDate', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('lookupCode', models.CharField(max_length=50, unique=True, validators=[django.core.validators.MinLengthValidator(2)])),
                ('carrier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='services', to='logistics.carrier')),
                ('createdByUser', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('modifiedByUser', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_modified', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdDate', models.DateTimeField(auto_now_add=True)),
                ('modifiedDate', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('lookupCode', models.CharField(max_length=50, unique=True, validators=[django.core.validators.MinLengthValidator(2)])),
                ('notes', models.TextField(blank=True)),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='warehouses', to='logistics.address')),
                ('createdByUser', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('modifiedByUser', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_modified', to=settings.AUTH_USER_MODEL)),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='warehouses', to='core.status')),
            ],
        ),
        migrations.AddIndex(
            model_name='address',
            index=models.Index(fields=['entityType', 'entityID'], name='logistics_a_entityT_7345f1_idx'),
        ),
        migrations.AddIndex(
            model_name='address',
            index=models.Index(fields=['country', 'state', 'city'], name='logistics_a_country_5cefab_idx'),
        ),
        migrations.AddIndex(
            model_name='carrier',
            index=models.Index(fields=['lookupCode'], name='logistics_c_lookupC_40287b_idx'),
        ),
        migrations.AddIndex(
            model_name='carrierservice',
            index=models.Index(fields=['lookupCode'], name='logistics_c_lookupC_d9c6e0_idx'),
        ),
        migrations.AddIndex(
            model_name='carrierservice',
            index=models.Index(fields=['carrier'], name='logistics_c_carrier_a49611_idx'),
        ),
        migrations.AddIndex(
            model_name='warehouse',
            index=models.Index(fields=['lookupCode'], name='logistics_w_lookupC_985b4c_idx'),
        ),
    ]
