# Generated by Django 5.1.5 on 2025-01-23 20:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0005_contact'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('is_primary', models.BooleanField(default=False)),
                ('address_type', models.CharField(choices=[('shipping', 'Shipping'), ('billing', 'Billing')], default='shipping', max_length=10)),
            ],
        ),
        migrations.RemoveIndex(
            model_name='contact',
            name='logistics_c_address_da12ea_idx',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='address',
        ),
        migrations.AddField(
            model_name='contactaddress',
            name='address',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='logistics.address'),
        ),
        migrations.AddField(
            model_name='contactaddress',
            name='contact',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='logistics.contact'),
        ),
        migrations.AddField(
            model_name='contactaddress',
            name='created_by_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='contactaddress',
            name='modified_by_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_modified', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='contact',
            name='addresses',
            field=models.ManyToManyField(related_name='contact_addresses', through='logistics.ContactAddress', to='logistics.address'),
        ),
        migrations.AddIndex(
            model_name='contactaddress',
            index=models.Index(fields=['contact', 'is_primary'], name='logistics_c_contact_a2599c_idx'),
        ),
        migrations.AddIndex(
            model_name='contactaddress',
            index=models.Index(fields=['address', 'address_type'], name='logistics_c_address_6a23de_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='contactaddress',
            unique_together={('contact', 'address', 'address_type')},
        ),
    ]
