# Generated by Django 5.1.5 on 2025-01-23 21:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0008_remove_address_logistics_a_entity__2b21b3_idx_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='position',
            new_name='title',
        ),
    ]
