# Generated by Django 5.1.5 on 2025-01-24 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0010_auto_20250124_1401'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='addresses',
            field=models.ManyToManyField(blank=True, related_name='contacts', to='logistics.address'),
        ),
    ]
