# Generated by Django 5.1.5 on 2025-01-21 21:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_role'),
        ('customers', '0004_alter_user_role_alter_user_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='users', to='core.role'),
        ),
        migrations.DeleteModel(
            name='Role',
        ),
    ]
