# Generated by Django 5.1.5 on 2025-01-22 15:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0007_project_carrier_project_warehouse'),
        ('logistics', '0002_alter_address_entitytype'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='logistics.carrierservice'),
        ),
    ]
