# Generated by Django 5.1.5 on 2025-01-22 16:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0008_project_service'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='created_date',
            new_name='createdDate',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='modified_date',
            new_name='modifiedDate',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='created_date',
            new_name='createdDate',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='modified_date',
            new_name='modifiedDate',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='modified_by',
        ),
        migrations.RemoveField(
            model_name='project',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='project',
            name='modified_by',
        ),
        migrations.AddField(
            model_name='customer',
            name='createdByUser',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='customer',
            name='modifiedByUser',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_modified', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='project',
            name='createdByUser',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='project',
            name='modifiedByUser',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_modified', to=settings.AUTH_USER_MODEL),
        ),
    ]
