# Generated by Django 5.1.5 on 2025-01-21 20:16

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('customers', '0001_initial'),
        ('logistics', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdDate', models.DateTimeField(auto_now_add=True)),
                ('modifiedDate', models.DateTimeField(auto_now=True)),
                ('className', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True)),
                ('isActive', models.BooleanField(default=True)),
                ('createdByUser', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('modifiedByUser', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_modified', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Order Classes',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdDate', models.DateTimeField(auto_now_add=True)),
                ('modifiedDate', models.DateTimeField(auto_now=True)),
                ('lookupCodeOrder', models.CharField(help_text='Unique order identifier', max_length=50, unique=True, validators=[django.core.validators.MinLengthValidator(2)])),
                ('lookupCodeShipment', models.CharField(help_text='Unique shipment identifier', max_length=50, unique=True, validators=[django.core.validators.MinLengthValidator(2)])),
                ('orderType', models.CharField(choices=[('INBOUND', 'Inbound'), ('OUTBOUND', 'Outbound')], help_text='INBOUND: Receiving inventory, OUTBOUND: Shipping to customers', max_length=8)),
                ('expectedDeliveryDate', models.DateTimeField()),
                ('notes', models.TextField(blank=True)),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='shipping_orders', to='logistics.address')),
                ('billingAddress', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='billing_orders', to='logistics.address')),
                ('carrier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='logistics.carrier')),
                ('createdByUser', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('modifiedByUser', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_modified', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='customers.project')),
                ('serviceType', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='logistics.carrierservice')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='core.status')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='logistics.warehouse')),
                ('orderClass', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='orders.orderclass')),
            ],
            options={
                'indexes': [models.Index(fields=['project', 'status'], name='orders_orde_project_2cb826_idx'), models.Index(fields=['lookupCodeOrder'], name='orders_orde_lookupC_e57bf5_idx'), models.Index(fields=['lookupCodeShipment'], name='orders_orde_lookupC_29abbd_idx'), models.Index(fields=['expectedDeliveryDate'], name='orders_orde_expecte_f0bb3c_idx')],
            },
        ),
    ]
