# Generated by Django 5.1.5 on 2025-01-22 19:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_auditlogs_core_auditl_entity_1c2026_idx_and_more'),
        ('customers', '0011_rename_lookupcode_customer_lookup_code_and_more'),
        ('inventory', '0003_remove_inventory_inventory_i_license_54c5e7_idx_and_more'),
        ('logistics', '0004_remove_address_logistics_a_entityt_7345f1_idx_and_more'),
        ('orders', '0006_rename_createdbyuser_order_created_by_user_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='order',
            name='orders_orde_lookupC_e57bf5_idx',
        ),
        migrations.RemoveIndex(
            model_name='order',
            name='orders_orde_lookupC_29abbd_idx',
        ),
        migrations.RemoveIndex(
            model_name='order',
            name='orders_orde_expecte_f0bb3c_idx',
        ),
        migrations.RemoveIndex(
            model_name='orderline',
            name='orders_orde_license_20129b_idx',
        ),
        migrations.RemoveIndex(
            model_name='orderline',
            name='orders_orde_serialN_78ce92_idx',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='billingAddress',
            new_name='billing_address',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='expectedDeliveryDate',
            new_name='expected_delivery_date',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='lookupCodeOrder',
            new_name='lookup_code_order',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='lookupCodeShipment',
            new_name='lookup_code_shipment',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='orderClass',
            new_name='order_class',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='orderType',
            new_name='order_type',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='serviceType',
            new_name='service_type',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='shippingAddress',
            new_name='shipping_address',
        ),
        migrations.RenameField(
            model_name='orderclass',
            old_name='className',
            new_name='class_name',
        ),
        migrations.RenameField(
            model_name='orderclass',
            old_name='isActive',
            new_name='is_active',
        ),
        migrations.RenameField(
            model_name='orderline',
            old_name='licensePlate',
            new_name='license_plate',
        ),
        migrations.RenameField(
            model_name='orderline',
            old_name='serialNumber',
            new_name='serial_number',
        ),
        migrations.RenameField(
            model_name='orderline',
            old_name='vendorLot',
            new_name='vendor_lot',
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['lookup_code_order'], name='orders_orde_lookup__d2462e_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['lookup_code_shipment'], name='orders_orde_lookup__18b53a_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['expected_delivery_date'], name='orders_orde_expecte_d41167_idx'),
        ),
        migrations.AddIndex(
            model_name='orderline',
            index=models.Index(fields=['license_plate'], name='orders_orde_license_3f5210_idx'),
        ),
        migrations.AddIndex(
            model_name='orderline',
            index=models.Index(fields=['serial_number'], name='orders_orde_serial__315ca6_idx'),
        ),
    ]
