# Generated by Django 5.1.5 on 2025-01-23 19:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_ordertype'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ordertype',
            options={'verbose_name_plural': 'Order Types'},
        ),
        migrations.RemoveIndex(
            model_name='ordertype',
            name='orders_orde_entity_d8373c_idx',
        ),
        migrations.AlterUniqueTogether(
            name='ordertype',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='ordertype',
            name='entity',
        ),
    ]
