# Generated by Django 5.1.5 on 2025-01-29 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0014_alter_order_expected_delivery_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordertype',
            name='is_active',
        ),
        migrations.AlterField(
            model_name='ordertype',
            name='description',
            field=models.CharField(blank=True),
        ),
    ]
