# Generated by Django 5.1.5 on 2025-01-22 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inventory',
            old_name='createdByUser',
            new_name='created_by_user',
        ),
        migrations.RenameField(
            model_name='inventory',
            old_name='createdDate',
            new_name='created_date',
        ),
        migrations.RenameField(
            model_name='inventory',
            old_name='modifiedByUser',
            new_name='modified_by_user',
        ),
        migrations.RenameField(
            model_name='inventory',
            old_name='modifiedDate',
            new_name='modified_date',
        ),
        migrations.RenameField(
            model_name='inventoryserialnumber',
            old_name='createdByUser',
            new_name='created_by_user',
        ),
        migrations.RenameField(
            model_name='inventoryserialnumber',
            old_name='createdDate',
            new_name='created_date',
        ),
        migrations.RenameField(
            model_name='inventoryserialnumber',
            old_name='modifiedByUser',
            new_name='modified_by_user',
        ),
        migrations.RenameField(
            model_name='inventoryserialnumber',
            old_name='modifiedDate',
            new_name='modified_date',
        ),
        migrations.RenameField(
            model_name='material',
            old_name='createdByUser',
            new_name='created_by_user',
        ),
        migrations.RenameField(
            model_name='material',
            old_name='createdDate',
            new_name='created_date',
        ),
        migrations.RenameField(
            model_name='material',
            old_name='modifiedByUser',
            new_name='modified_by_user',
        ),
        migrations.RenameField(
            model_name='material',
            old_name='modifiedDate',
            new_name='modified_date',
        ),
        migrations.RenameField(
            model_name='uom',
            old_name='createdByUser',
            new_name='created_by_user',
        ),
        migrations.RenameField(
            model_name='uom',
            old_name='createdDate',
            new_name='created_date',
        ),
        migrations.RenameField(
            model_name='uom',
            old_name='modifiedByUser',
            new_name='modified_by_user',
        ),
        migrations.RenameField(
            model_name='uom',
            old_name='modifiedDate',
            new_name='modified_date',
        ),
    ]
