# Generated by Django 5.1.5 on 2025-01-27 18:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_alter_inventory_license_plate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='license_plate_id',
            field=models.CharField(blank=True, max_length=50, unique=True, validators=[django.core.validators.MinLengthValidator(2)]),
        ),
    ]
