# Generated by Django 5.1.5 on 2025-01-27 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_remove_inventory_last_updated_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='description',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
