# Generated by Django 5.1.5 on 2025-01-27 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_alter_material_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uom',
            name='description',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
