# Generated by Django 5.1.5 on 2025-01-28 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0013_alter_material_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
