# Generated by Django 5.1.5 on 2025-01-22 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0009_rename_created_date_customer_createddate_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='createdByUser',
            new_name='created_by_user',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='createdDate',
            new_name='created_date',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='modifiedByUser',
            new_name='modified_by_user',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='modifiedDate',
            new_name='modified_date',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='createdByUser',
            new_name='created_by_user',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='createdDate',
            new_name='created_date',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='modifiedByUser',
            new_name='modified_by_user',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='modifiedDate',
            new_name='modified_date',
        ),
    ]
