# Generated by Django 5.1.5 on 2025-01-22 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0010_rename_createdbyuser_customer_created_by_user_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='lookupCode',
            new_name='lookup_code',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='outputFormat',
            new_name='output_format',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='lookupCode',
            new_name='lookup_code',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='ordersPrefix',
            new_name='orders_prefix',
        ),
    ]
