# Generated by Django 5.1.5 on 2025-01-24 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0011_rename_lookupcode_customer_lookup_code_and_more'),
        ('logistics', '0009_rename_position_contact_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='carrier',
        ),
        migrations.RemoveField(
            model_name='project',
            name='service',
        ),
        migrations.RemoveField(
            model_name='project',
            name='warehouse',
        ),
        migrations.AddField(
            model_name='project',
            name='carriers',
            field=models.ManyToManyField(blank=True, related_name='projects', to='logistics.carrier'),
        ),
        migrations.AddField(
            model_name='project',
            name='services',
            field=models.ManyToManyField(blank=True, related_name='projects', to='logistics.carrierservice'),
        ),
        migrations.AddField(
            model_name='project',
            name='warehouses',
            field=models.ManyToManyField(blank=True, related_name='projects', to='logistics.warehouse'),
        ),
    ]
