# Generated by Django 5.1.5 on 2025-01-22 16:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_role'),
        ('inventory', '0001_initial'),
        ('orders', '0003_rename_address_order_shippingaddress'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdDate', models.DateTimeField(auto_now_add=True)),
                ('modifiedDate', models.DateTimeField(auto_now=True)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('lot', models.CharField(blank=True, max_length=50)),
                ('vendorLot', models.CharField(blank=True, max_length=50)),
                ('notes', models.TextField(blank=True)),
                ('createdByUser', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('licensePlate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='order_lines', to='inventory.inventory')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_lines', to='inventory.material')),
                ('modifiedByUser', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_modified', to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lines', to='orders.order')),
                ('serialNumber', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='order_lines', to='inventory.inventoryserialnumber')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_lines', to='core.status')),
            ],
            options={
                'indexes': [models.Index(fields=['order', 'material'], name='orders_orde_order_i_77d316_idx'), models.Index(fields=['licensePlate'], name='orders_orde_license_20129b_idx'), models.Index(fields=['serialNumber'], name='orders_orde_serialN_78ce92_idx')],
            },
        ),
    ]
