# Generated by Django 5.1.5 on 2025-01-22 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_orderline'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderline',
            name='status',
        ),
    ]
