# Generated by Django 5.1.5 on 2025-01-22 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_remove_orderline_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='createdByUser',
            new_name='created_by_user',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='createdDate',
            new_name='created_date',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='modifiedByUser',
            new_name='modified_by_user',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='modifiedDate',
            new_name='modified_date',
        ),
        migrations.RenameField(
            model_name='orderclass',
            old_name='createdByUser',
            new_name='created_by_user',
        ),
        migrations.RenameField(
            model_name='orderclass',
            old_name='createdDate',
            new_name='created_date',
        ),
        migrations.RenameField(
            model_name='orderclass',
            old_name='modifiedByUser',
            new_name='modified_by_user',
        ),
        migrations.RenameField(
            model_name='orderclass',
            old_name='modifiedDate',
            new_name='modified_date',
        ),
        migrations.RenameField(
            model_name='orderline',
            old_name='createdByUser',
            new_name='created_by_user',
        ),
        migrations.RenameField(
            model_name='orderline',
            old_name='createdDate',
            new_name='created_date',
        ),
        migrations.RenameField(
            model_name='orderline',
            old_name='modifiedByUser',
            new_name='modified_by_user',
        ),
        migrations.RenameField(
            model_name='orderline',
            old_name='modifiedDate',
            new_name='modified_date',
        ),
    ]
