# Generated by Django 5.1.5 on 2025-01-23 21:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0008_remove_address_logistics_a_entity__2b21b3_idx_and_more'),
        ('orders', '0010_order_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='contact',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='logistics.contact'),
            preserve_default=False,
        ),
    ]
