# Generated by Django 5.1.5 on 2025-01-28 15:59

import apps.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0012_alter_orderclass_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='lookup_code_order',
            field=models.CharField(help_text='Unique order identifier', max_length=50, unique=True, validators=[apps.core.validators.validate_lookup_code]),
        ),
        migrations.AlterField(
            model_name='order',
            name='lookup_code_shipment',
            field=models.CharField(help_text='Unique shipment identifier', max_length=50, unique=True, validators=[apps.core.validators.validate_lookup_code]),
        ),
    ]
