# Generated by Django 5.1.5 on 2025-01-28 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0013_alter_order_lookup_code_order_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='expected_delivery_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
